version: '3.8'
services:
  stt:
    build: ./stt
    ports: ["8001:8001"]
    env_file: ./stt/.env
  lang:
    build: ./lang
    ports: ["8002:8002"]
    env_file: ./lang/.env
  gpt:
    build: ./gpt
    ports: ["8003:8003"]
    env_file: ./gpt/.env
  tts:
    build: ./tts
    ports: ["8004:8004"]
    env_file: ./tts/.env
  lead_sender:
    build: ./lead_sender
    ports: ["8005:8005"]
    env_file: ./lead_sender/.env
  call_handler:
    build: ./call_handler
    ports: ["8006:8006"]
    env_file: ./call_handler/.env
  logger:
    build: ./logger
    ports: ["8007:8007"]
    env_file: ./logger/.env
  storage:
    build: ./storage
    ports: ["8008:8008"]
    env_file: ./storage/.env 