# Глобальные настройки TruckAI
# Пример структуры:
openai_api_key: "YOUR_OPENAI_KEY"
twilio_account_sid: "YOUR_TWILIO_SID"
twilio_auth_token: "YOUR_TWILIO_TOKEN"
tts_provider: "google"
stt_provider: "whisper" 